### PR TITLE
Fixed the frontend errors and solution path for ca-certificate error.

### PR DESCRIPTION
**Pull request by Kodalem**
Added proposed guidance in the image generation and README if one cannot install the image using the Rosetta 2 in case of ca-certificate throwing illegal instruction error.

Also resolved the missing library for the frontend, per [this](https://github.com/moby/moby/issues/27988)

```
...
115.2 Processing triggers for ca-certificates (20230311 ubuntu0.22.04.1)...
115.2 Updating certificates in /etc/ssl/certs...
116.6 Illegal instruction
...
121.8 Errors were encountered while processing:
121.8  ca-certificates
121.8 E: Sub-process /usr/bin/dpkg returned an error code (1)
------

 2 warnings found (use docker --debug to expand):
 - FromPlatformFlagConstDisallowed: FROM --platform flag should not use constant value "linux/amd64" (line 3)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 53)
Dockerfile:10
--------------------
   9 |     # install gui
  10 | >>> RUN apt install -y --no-install-recommends --allow-unauthenticated \
  11 | >>> dbus dbus-x11 x11-utils xorg alsa-utils mesa-utils net-tools \
  12 | >>> libgl1-mesa-dri gtk2-engines lxappearance fonts-droid-fallback sudo firefox \
  13 | >>> ubuntu-gnome-default-settings curl gnupg lxde arc-theme \
  14 | >>> gtk2-engines-murrine gtk2-engines-pixbuf gnome-themes-standard nano xterm
  15 |
--------------------
ERROR: failed to solve: process "/bin/sh -c apt install -y --no-install-recommends --allow-unauthenticated dbus dbus-x11 x11-utils xorg alsa-utils mesa-utils net-tools libgl1-mesa-dri gtk2-engines lxappearance fonts-droid-fallback sudo firefox ubuntu-gnome-default-settings curl gnupg lxde arc-theme gtk2-engines-murrine gtk2-engines-pixbuf gnome-themes-standard nano xterm" did not complete successfully: exit code: 100

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/ae9xosgwnd9q8s6ox0ywssjh4
Docker image generation failed!
```

### CODE REVIEW

**Review by ichi4096 — CHANGES_REQUESTED** [review]
The `softwareupdate --install-rosetta --agree-to-license` line should be executed automatically in the setup.sh, which I forgot when I rewrote the whole thing. The readme should contain a notice that Rosetta 2 will be installed as part of the setup.

I cannot reproduce the APT frontend issues You mention. If You don't experience them Yourself, then I suggest not installing further packages. However, since the ca-certificates installation seems to be messing with the Rosetta 2 emulation of some people, I agree that it can be in a separate apt command.

The notice in gen_image.sh should be removed as the command should be executed by setup.sh anyway.

Thank You for taking the time and if You implement the changes I mention or convince me otherwise I'll approve the merge request.

**Comment by Kodalem** [comment]
I have added this following line to remove the pesky errors, maybe there is changed installation variables, which adds this argument anyways when initializing the whole container. I have done this instead of installing the extra missing package to remove overhead. There might be argument for adding more feedback in the frontend when there's some crash log, but not sure if it is of any use.
```
ARG DEBIAN_FRONTEND=noninteractive
RUN ...
```
To note that it is very discouraged to set it as ENV, per this [discussion](https://github.com/moby/moby/issues/4032#issuecomment-34597177), so there's an ARG instead.

Also expanded the comprehensive-er Rosetta installation script, where it just in case asks for user's consent to install it if they have not done it. It'll check if it is installed already instead. **Although I have added still the note** onto the bash echo that in the case of the illegal instruction error that you should try reinstalling it.

**Review by ichi4096 — CHANGES_REQUESTED** [review]
I agree with the Dockerfile and readme so far, still I want to check myself whether the `ARG` doesn't break anything when installing (later today). As for setup.sh, since Rosetta is required anyway, I'd rather the user is prompted something like "This setup is about to install Rosetta 2 (required). Proceed? [Y/n]". Like this, no additional prompts related to Rosetta are required.

**Comment by Kodalem** [comment]
I have reinstalled the new container with new setting, all appears to be in working order - just needs someone else to also verify and confirm this. The install script tells the user that if they install from this, they also agree with Apple's Rosetta license - does not seem to be a good practice to not ask for user consent before installation which has license agreements.

**Comment by ichi4096** [comment]
Checking whether Rosetta is installed should be done [via this method](https://apple.stackexchange.com/a/464165) since `pgrep` only checks whether the Rosetta daemon has been started. However, it'd be easier to just execute the installation command because it takes practically no time if Rosetta is already installed. You are right that Rosetta installation and agreeing to the terms requires explicit user consent. Maybe include the fact that one also automatically agrees to Xilinx and third party terms.

**Comment by ichi4096** [comment]
It's been a week so I'll merge Your PR but change it like I already described.

**Pull request merged**
